# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warc_name', models.TextField()),
                ('warc_dir', models.TextField()),
                ('timestamp', models.CharField(max_length=255)),
                ('submitted_url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_archive1', to='compare.Archive')),
                ('archive2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_archive2', to='compare.Archive')),
            ],
        ),
    ]
