# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WDTArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warc_name', models.TextField()),
                ('warc_dir', models.TextField()),
                ('timestamp', models.CharField(max_length=255)),
                ('submitted_url', models.URLField(max_length=1000)),
                ('compare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.Compare')),
            ],
        ),
    ]
