# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdtarchive',
            name='compare',
        ),
        migrations.AddField(
            model_name='compare',
            name='warc1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_warc1', to='compare.WDTArchive'),
        ),
        migrations.AddField(
            model_name='compare',
            name='warc2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_warc2', to='compare.WDTArchive'),
        ),
    ]
