# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='warc_dir',
        ),
        migrations.AlterField(
            model_name='archive',
            name='submitted_url',
            field=models.URLField(db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='archive',
            name='timestamp',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
