# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20171215_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('content_type', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('m', 'missing'), ('a', 'added'), ('c', 'changed'), ('u', 'unchanged'), ('p', 'pending')], default='p', max_length=1)),
                ('payload', models.TextField()),
                ('hash', models.CharField(max_length=1000)),
                ('headers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minhash', models.FloatField()),
                ('simhash', models.FloatField()),
                ('sequence_match', models.FloatField()),
                ('html_deleted', models.TextField()),
                ('html_added', models.TextField()),
                ('html_combined', models.TextField()),
                ('resource1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource1', to='compare.Resource')),
                ('resource2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource2', to='compare.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compare',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='resources',
            field=models.ManyToManyField(to='compare.Resource'),
        ),
    ]
