# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20180121_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submitted_url',
            field=models.BooleanField(default=False),
        ),
    ]
