# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_resource_submitted_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='resource_compares',
            field=models.ManyToManyField(to='compare.ResourceCompare'),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_combined',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_deleted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='minhash',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='sequence_match',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='simhash',
            field=models.FloatField(null=True),
        ),
    ]
