# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 16:09
from __future__ import unicode_literals

import compare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20180126_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_added',
            field=models.FileField(null=True, upload_to=compare.models.compare_file_dir_path),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_combined',
            field=models.FileField(null=True, upload_to=compare.models.compare_file_dir_path),
        ),
        migrations.AlterField(
            model_name='resourcecompare',
            name='html_deleted',
            field=models.FileField(null=True, upload_to=compare.models.compare_file_dir_path),
        ),
    ]
