# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20180126_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecompare',
            old_name='minhash',
            new_name='change',
        ),
        migrations.RemoveField(
            model_name='resourcecompare',
            name='sequence_match',
        ),
        migrations.RemoveField(
            model_name='resourcecompare',
            name='simhash',
        ),
    ]
