# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0007_auto_20180126_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=3000),
        ),
    ]
