# Generated by Django 2.0.1 on 2018-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_compare_submitted_url_compare_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecompare',
            name='submitted_url',
            field=models.BooleanField(default=False),
        ),
    ]
