# Generated by Django 2.0.1 on 2018-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_resourcecompare_submitted_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='timestamp',
            new_name='requested_date',
        ),
        migrations.AddField(
            model_name='archive',
            name='actual_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
