# Generated by Django 2.0.1 on 2018-05-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_auto_20180131_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecompare',
            old_name='submitted_url',
            new_name='is_submitted_url',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='submitted_url',
            new_name='is_submitted_url',
        ),
    ]
